#!/bin/bash

goldify() {
    if [ -z "$1" ]; then
        echo "Usage: goldify <path-to-icns>"
        return 1
    fi

    INPUT="$1"

    if [ ! -f "$INPUT" ]; then
        echo "File not found: $INPUT"
        return 1
    fi

    if ! command -v iconutil >/dev/null 2>&1; then
        echo "Error: iconutil is required but was not found."
        return 1
    fi

    if ! command -v sips >/dev/null 2>&1; then
        echo "Error: sips is required but was not found."
        return 1
    fi

    WORKDIR="$(mktemp -d)"
    ICONSET="$WORKDIR/icon.iconset"
    OUTPUT="$WORKDIR/goldifyicon.icns"

    trap 'rm -rf "$WORKDIR"' RETURN

    # Convert ICNS -> iconset
    if ! iconutil -c iconset "$INPUT" -o "$ICONSET"; then
        echo "Error: could not convert ICNS to iconset."
        return 1
    fi

    # Gold color.
    # sRGB values corresponding to a gold/yellow tone.
    GOLD_R=255
    GOLD_G=190
    GOLD_B=40

    # Process every PNG in the iconset.
    for PNG in "$ICONSET"/*.png; do
        [ -f "$PNG" ] || continue

        # Desaturate first, then colorize using sips.
        # This preserves the icon's luminance/alpha while giving it
        # a consistent gold appearance.
        sips \
            --matchTo '/System/Library/ColorSync/Profiles/sRGB Profile.icc' \
            --setProperty formatOptions 100 \
            "$PNG" >/dev/null 2>&1 || true

        # Apply a gold color tint using Core Image via a temporary
        # solid-color overlay generated by sips.
        TMP="$WORKDIR/$(basename "$PNG").tmp.png"

        cp "$PNG" "$TMP"

        # Convert the image to grayscale first.
        sips --setProperty formatOptions 100 "$TMP" >/dev/null 2>&1 || true

        # Use macOS's built-in Python if available; otherwise use
        # the Core Image command-line tools below.
        if command -v swift >/dev/null 2>&1; then
            swift - "$PNG" "$GOLD_R" "$GOLD_G" "$GOLD_B" <<'SWIFT'
import Foundation
import CoreImage
import ImageIO

let args = CommandLine.arguments
guard args.count >= 5 else { exit(1) }

let path = args[1]
let r = Float(args[2])! / 255.0
let g = Float(args[3])! / 255.0
let b = Float(args[4])! / 255.0

let url = URL(fileURLWithPath: path)

guard let input = CIImage(contentsOf: url) else {
    exit(1)
}

let filter = CIFilter(name: "CIColorMonochrome")!
filter.setValue(input, forKey: kCIInputImageKey)
filter.setValue(CIColor(red: CGFloat(r), green: CGFloat(g), blue: CGFloat(b)), forKey: kCIInputColorKey)
filter.setValue(1.0, forKey: kCIInputIntensityKey)

guard let output = filter.outputImage else {
    exit(1)
}

let context = CIContext()

guard let destination = CGImageDestinationCreateWithURL(
    url as CFURL,
    "public.png" as CFString,
    1,
    nil
) else {
    exit(1)
}

guard let cgImage = context.createCGImage(output, from: output.extent) else {
    exit(1)
}

CGImageDestinationAddImage(destination, cgImage, nil)

if !CGImageDestinationFinalize(destination) {
    exit(1)
}
SWIFT
        else
            echo "Error: Swift is required to goldify the icon."
            return 1
        fi
    done

    # Rebuild ICNS
    if ! iconutil -c icns "$ICONSET" -o "$OUTPUT"; then
        echo "Error: could not create gold ICNS."
        return 1
    fi

    # Copy to the standard location expected by your launcher script.
    cp "$OUTPUT" /tmp/goldifyicon.icns

    echo "Wrote /tmp/goldifyicon.icns"
}

OGPATH=$(
osascript <<'EOF'
set selectedApp to choose file ¬
	with prompt "Select an application (can be in anywhere, file browser on the left, but system apps almost never work, no patch for that rn)" ¬
	default location (path to applications folder) ¬
	of type {"app"}

POSIX path of selectedApp
EOF
)

APP_NAME="$(basename "$OGPATH" .app)"
NEWPATH="$HOME/Library/Printers/$APP_NAME.app"

mkdir -p "$HOME/Library/Printers"
mkdir -p "$HOME/packages"

cp -R "$OGPATH" "$NEWPATH"

if [[ -z "$NEWPATH" ]]; then
    echo "Usage: $0 /path/to/App.app"
    echo "   or: NEWPATH=/path/to/App.app $0"
    exit 1
fi

if [[ ! -d "$NEWPATH" || "$NEWPATH" != *.app ]]; then
    echo "Error: '$NEWPATH' is not a valid .app bundle."
    exit 1
fi

INFO_PLIST="$NEWPATH/Contents/Info.plist"
MACOS_DIR="$NEWPATH/Contents/MacOS"

if [[ ! -f "$INFO_PLIST" ]]; then
    echo "Error: Info.plist not found."
    exit 1
fi

if [[ ! -d "$MACOS_DIR" ]]; then
    echo "Error: Contents/MacOS not found."
    exit 1
fi

# Generate a random alphanumeric name, starting with a letter.
random_name() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 12
    echo
}

OLD_EXECUTABLE=$(/usr/libexec/PlistBuddy -c "Print :CFBundleExecutable" "$INFO_PLIST")

if [[ -z "$OLD_EXECUTABLE" || ! -f "$MACOS_DIR/$OLD_EXECUTABLE" ]]; then
    echo "Error: executable '$OLD_EXECUTABLE' not found in Contents/MacOS."
    exit 1
fi

NEW_NAME="$(random_name)"
NEW_BUNDLE_ID="com.$(random_name).$(random_name)"
NEW_EXECUTABLE="$NEW_NAME"

echo "App:              $NEWPATH"
echo "Old executable:   $OLD_EXECUTABLE"
echo "New executable:   $NEW_EXECUTABLE"
echo "New bundle ID:    $NEW_BUNDLE_ID"

# Rename the actual Mach-O executable.
mv "$MACOS_DIR/$OLD_EXECUTABLE" "$MACOS_DIR/$NEW_EXECUTABLE"

# Update Info.plist.
/usr/libexec/PlistBuddy -c "Set :CFBundleExecutable $NEW_EXECUTABLE" "$INFO_PLIST"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $NEW_BUNDLE_ID" "$INFO_PLIST"

xattr -dr com.apple.quarantine "$NEWPATH"
codesign --force --deep -s - "$NEWPATH"

# create launcher script
# Create launcher app
LAUNCHER="$HOME/Desktop/Launch $APP_NAME.app"
LAUNCHER_CONTENTS="$LAUNCHER/Contents"
LAUNCHER_MACOS="$LAUNCHER_CONTENTS/MacOS"
LAUNCHER_RESOURCES="$LAUNCHER_CONTENTS/Resources"

rm -rf "$LAUNCHER"

mkdir -p "$LAUNCHER_MACOS" "$LAUNCHER_RESOURCES"

# Find the source app's icon
ICON_FILE=$(
    /usr/libexec/PlistBuddy -c "Print :CFBundleIconFile" \
    "$NEWPATH/Contents/Info.plist" 2>/dev/null || true
)

if [[ -z "$ICON_FILE" ]]; then
    ICON_FILE="AppIcon.icns"
elif [[ "$ICON_FILE" != *.icns ]]; then
    ICON_FILE="${ICON_FILE}.icns"
fi

SOURCE_ICON="$NEWPATH/Contents/Resources/$ICON_FILE"
GOLD_ICON="/tmp/goldifyicon.icns"
DEST_ICON="$LAUNCHER_RESOURCES/Launcher.icns"

# Goldify the app icon
if [[ -f "$SOURCE_ICON" ]]; then
    echo "Goldifying icon: $SOURCE_ICON"

    # Run your goldify script.
    # Change /usr/local/bin/goldify if your script lives somewhere else.
    goldify "$SOURCE_ICON"

    # goldify writes to /tmp/goldifyicon.icns
    if [[ -f "$GOLD_ICON" ]]; then
        cp "$GOLD_ICON" "$DEST_ICON"
    else
        echo "Error: goldify did not create $GOLD_ICON"
        exit 1
    fi
else
    echo "Warning: Could not find source icon:"
    echo "  $SOURCE_ICON"
fi

# Create Info.plist
cat > "$LAUNCHER_CONTENTS/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0//EN"
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>

    <key>CFBundleDisplayName</key>
    <string>Launch $APP_NAME</string>

    <key>CFBundleExecutable</key>
    <string>Launch $APP_NAME</string>

    <key>CFBundleIconFile</key>
    <string>Launcher.icns</string>

    <key>CFBundleIdentifier</key>
    <string>com.launcher.$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9').launcher</string>

    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>

    <key>CFBundleName</key>
    <string>Launch $APP_NAME</string>

    <key>CFBundlePackageType</key>
    <string>APPL</string>

    <key>CFBundleShortVersionString</key>
    <string>1.0</string>

    <key>CFBundleVersion</key>
    <string>1</string>
</dict>
</plist>
EOF

# Create launcher executable
cat > "$LAUNCHER_MACOS/Launch $APP_NAME" <<EOF
#!/bin/bash
exec /usr/bin/open -- "$NEWPATH"
EOF

chmod +x "$LAUNCHER_MACOS/Launch $APP_NAME"

# Register launcher with LaunchServices
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$LAUNCHER" >/dev/null 2>&1 || true

# Register launcher with LaunchServices
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"

"$LSREGISTER" -f "$LAUNCHER" >/dev/null 2>&1 || true

# ------------------------------------------------------------
# Pin launcher to Dock using only built-in macOS tools
# No dockutil / Homebrew / Python / Xcode required
# ------------------------------------------------------------

DOCK_PLIST="$HOME/Library/Preferences/com.apple.dock.plist"
PLISTBUDDY="/usr/libexec/PlistBuddy"

if [[ ! -f "$DOCK_PLIST" ]]; then
    echo "Error: Dock plist not found: $DOCK_PLIST"
    exit 1
fi

echo "Pinning launcher to Dock..."

# Backup Dock plist
DOCK_BACKUP="$DOCK_PLIST.backup.$(date +%Y%m%d%H%M%S)"
cp "$DOCK_PLIST" "$DOCK_BACKUP"

# Use PlistBuddy's Print command and count actual array entries.
# Do NOT use awk; it can choke on localized/multibyte output.
APP_COUNT=0

while IFS= read -r LINE; do
    if [[ "$LINE" == "Dict {" || "$LINE" == "    Dict {" ]]; then
        ((APP_COUNT++)) || true
    fi
done < <(
    "$PLISTBUDDY" -c "Print :persistent-apps" "$DOCK_PLIST" 2>/dev/null
)

# If the count failed, abort rather than corrupting the Dock plist.
if [[ "$APP_COUNT" -le 0 ]]; then
    echo "Error: Could not determine existing Dock entries."
    echo "Dock plist backed up to:"
    echo "  $DOCK_BACKUP"
    exit 1
fi

# PlistBuddy arrays are zero-indexed.
# APP_COUNT is therefore the next index at which we append.
NEW_INDEX="$APP_COUNT"

echo "Existing Dock apps: $APP_COUNT"
echo "New Dock index: $NEW_INDEX"

# Add the Dock tile.
"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX dict" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-type string file-tile" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data dict" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data:file-data dict" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data:file-data:_CFURLString string $LAUNCHER" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data:file-data:_CFURLStringType integer 0" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data:file-label string Launch $APP_NAME" \
    "$DOCK_PLIST"

"$PLISTBUDDY" -c \
    "Add :persistent-apps:$NEW_INDEX:tile-data:file-type integer 41" \
    "$DOCK_PLIST"

# Tell LaunchServices about the launcher.
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"

"$LSREGISTER" -f "$LAUNCHER" >/dev/null 2>&1 || true

# Reload preferences and restart Dock.
killall cfprefsd >/dev/null 2>&1 || true
killall Dock >/dev/null 2>&1 || true

echo "Pinned to Dock:"
echo "  $LAUNCHER"